[features]
seeds = false
skip-lint = false
[programs.localnet]
backend = "H8T4jm38UKJp2GBEG5s4X2NFT4U87CfLJVtTZVnh3zVs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/coach/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
