import './globals.css'
import type { Metadata } from 'next'
import { WalletAdapter } from './components/hooks/WalletAdapter'
import { ENV } from './components/models/env'
import Head from 'next/head'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Head>
          <title>Solana-GPT</title>
          <meta name="description" content="Pay Per Question!" />
        </Head>
        <WalletAdapter rpcUrl={ENV.rpcEndpoint} showTestWallets={ENV.showTestWallets}>
          {children}
        </WalletAdapter>
      </body>
    </html>
  );
}
